Ignore TripleO jobs for other centos versions in CBS updates
When running tripleo to gate changes in CBS tags we need to select the
jobs not only based on phase (testing or release), version of openstack
but also based on version of CentOs Stream. i.e. if we are updating
nfv9s-openvswitch-2-testing, jobs for CS8 should be skipped.

This review is improving the initial check where we find if a job is
required or can be ignored to include this criteria.

Change-Id: I85fc7e14f6d7062f66b521bec50df01ec53de92d

diff --git a/playbooks/run-rdoinfo-cbs-centos9.yaml b/playbooks/run-rdoinfo-cbs-centos9.yaml
--- a/playbooks/run-rdoinfo-cbs-centos9.yaml
+++ b/playbooks/run-rdoinfo-cbs-centos9.yaml
@@ -37,16 +37,27 @@
 
           REQUIRED=0
           CREPOS_FILE=changed_repos.txt
-
-          if [ -z "{{ rdoinfo_phase|default("") }}" -o -z "{{ rdoinfo_release|default("") }}" ]; then
-              echo "ERROR in job definition"
-              exit 1
-          fi
+          PROJECT="{{ zuul.project.name }}"
+          DIST_VER="{{ centos_releasever }}"
 
           if [ "{{ rdoinfo_release }}" = "master" ]; then
               RELEASE="{{ master_release }}"
           else
               RELEASE="{{ rdoinfo_release }}"
+          fi
+
+          case $PROJECT in
+          rdoinfo)
+            REPO="cloud${DIST_VER}-openstack-$RELEASE-$PHASE"
+          ;;
+          nfvinfo)
+            REPO="nfv${DIST_VER}-openvswitch-2-$PHASE"
+          ;;
+          esac
+
+          if [ -z "{{ rdoinfo_phase|default("") }}" -o -z "{{ rdoinfo_release|default("") }}" ]; then
+              echo "ERROR in job definition"
+              exit 1
           fi
 
           # Set log path
@@ -59,7 +70,7 @@
           # If we could not find a working repository, give up
           curl -o $CREPOS_FILE -sf "$logs/repos/changed_repos.txt" || exit 1
 
-          if ! grep -q -E "($RELEASE|openvswitch-2)-{{ rdoinfo_phase }}" $CREPOS_FILE; then
+          if ! grep -q -E ${REPO} $CREPOS_FILE; then
               echo "INFO: this test is not required"| tee not_required
               exit 0
           fi
